import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

// P17: bundle the Templater API as a standalone, Obsidian-free JS module.
// The user drops liftoscript-api.js into their Templater "Scripts" folder.
const apiContext = await esbuild.context({
	banner: {
		js: "/* Liftoscript API for Templater (tp.user.liftoscript_api) */",
	},
	entryPoints: ["templaterApi.ts"],
	bundle: true,
	format: "cjs",
	target: "es2018",
	platform: "node",
	logLevel: "info",
	treeShaking: true,
	outfile: "liftoscript-api.js",
});

if (prod) {
	await context.rebuild();
	await apiContext.rebuild();
	await apiContext.dispose();
	process.exit(0);
} else {
	await context.watch();
	await apiContext.watch();
}
